package com.eliseu;

public class main {
    public static void main(String[] args) {
//        String input = "records[0].CardName=ELISEU\nrecords[1].CardName=JOAO";

        String input = "found=9\n" +
                "records[0].CardName=ELISEU\n" +
                "records[0].CardNo=\n" +
                "records[0].CardStatus=0\n" +
                "records[0].CardType=0\n" +
                "records[0].CitizenIDNo=\n" +
                "records[0].Doors[0]=0\n" +
                "records[0].DynamicCheckCode=\n" +
                "records[0].FirstEnter=false\n" +
                "records[0].Handicap=false\n" +
                "records[0].IsValid=false\n" +
                "records[0].Password=\n" +
                "records[0].RecNo=1\n" +
                "records[0].RepeatEnterRouteTimeout=4294967295\n" +
                "records[0].TimeSections[0]=255\n" +
                "records[0].UseTime=200\n" +
                "records[0].UserID=1\n" +
                "records[0].UserType=0\n" +
                "records[0].VTOPosition=\n" +
                "records[0].ValidDateEnd=2037-12-31 23:59:59\n" +
                "records[0].ValidDateStart=2000-01-01 00:02:52\n" +
                "records[1].CardName=GABRIEL MPE\n" +
                "records[1].CardNo=\n" +
                "records[1].CardStatus=0\n" +
                "records[1].CardType=0\n" +
                "records[1].CitizenIDNo=\n" +
                "records[1].Doors[0]=0\n" +
                "records[1].DynamicCheckCode=\n" +
                "records[1].FirstEnter=false\n" +
                "records[1].Handicap=false\n" +
                "records[1].IsValid=false\n" +
                "records[1].Password=\n" +
                "records[1].RecNo=2\n" +
                "records[1].RepeatEnterRouteTimeout=4294967295\n" +
                "records[1].TimeSections[0]=255\n" +
                "records[1].UseTime=200\n" +
                "records[1].UserID=2\n" +
                "records[1].UserType=0\n" +
                "records[1].VTOPosition=\n" +
                "records[1].ValidDateEnd=2037-12-31 23:59:59\n" +
                "records[1].ValidDateStart=2000-01-01 06:47:41\n" +
                "records[2].CardName=ROGER MPE\n" +
                "records[2].CardNo=\n" +
                "records[2].CardStatus=0\n" +
                "records[2].CardType=0\n" +
                "records[2].CitizenIDNo=\n" +
                "records[2].Doors[0]=0\n" +
                "records[2].DynamicCheckCode=\n" +
                "records[2].FirstEnter=false\n" +
                "records[2].Handicap=false\n" +
                "records[2].IsValid=false\n" +
                "records[2].Password=\n" +
                "records[2].RecNo=3\n" +
                "records[2].RepeatEnterRouteTimeout=4294967295\n" +
                "records[2].TimeSections[0]=255\n" +
                "records[2].UseTime=200\n" +
                "records[2].UserID=3\n" +
                "records[2].UserType=0\n" +
                "records[2].VTOPosition=\n" +
                "records[2].ValidDateEnd=2037-12-31 23:59:59\n" +
                "records[2].ValidDateStart=2000-01-01 06:48:34\n" +
                "records[3].CardName=Jocemar Up\n" +
                "records[3].CardNo=AF79FCC1\n" +
                "records[3].CardStatus=0\n" +
                "records[3].CardType=0\n" +
                "records[3].CitizenIDNo=\n" +
                "records[3].Doors[0]=0\n" +
                "records[3].DynamicCheckCode=\n" +
                "records[3].FirstEnter=false\n" +
                "records[3].Handicap=false\n" +
                "records[3].IsValid=false\n" +
                "records[3].Password=234\n" +
                "records[3].RecNo=5\n" +
                "records[3].RepeatEnterRouteTimeout=4294967295\n" +
                "records[3].TimeSections[0]=255\n" +
                "records[3].UseTime=0\n" +
                "records[3].UserID=5\n" +
                "records[3].UserType=0\n" +
                "records[3].VTOPosition=\n" +
                "records[3].ValidDateEnd=2037-01-02 01:00:00\n" +
                "records[3].ValidDateStart=2019-01-02 00:00:00\n" +
                "records[4].CardName=Odair Up\n" +
                "records[4].CardNo=AF79FCC0\n" +
                "records[4].CardStatus=0\n" +
                "records[4].CardType=0\n" +
                "records[4].CitizenIDNo=\n" +
                "records[4].Doors[0]=0\n" +
                "records[4].DynamicCheckCode=\n" +
                "records[4].FirstEnter=false\n" +
                "records[4].Handicap=false\n" +
                "records[4].IsValid=false\n" +
                "records[4].Password=234\n" +
                "records[4].RecNo=6\n" +
                "records[4].RepeatEnterRouteTimeout=4294967295\n" +
                "records[4].TimeSections[0]=255\n" +
                "records[4].UseTime=0\n" +
                "records[4].UserID=4\n" +
                "records[4].UserType=0\n" +
                "records[4].VTOPosition=\n" +
                "records[4].ValidDateEnd=2037-01-02 01:00:00\n" +
                "records[4].ValidDateStart=2019-01-02 00:00:00\n" +
                "records[5].CardName=Nicolas Up\n" +
                "records[5].CardNo=AF79FCC2\n" +
                "records[5].CardStatus=0\n" +
                "records[5].CardType=0\n" +
                "records[5].CitizenIDNo=\n" +
                "records[5].Doors[0]=0\n" +
                "records[5].DynamicCheckCode=\n" +
                "records[5].FirstEnter=false\n" +
                "records[5].Handicap=false\n" +
                "records[5].IsValid=false\n" +
                "records[5].Password=234\n" +
                "records[5].RecNo=7\n" +
                "records[5].RepeatEnterRouteTimeout=4294967295\n" +
                "records[5].TimeSections[0]=255\n" +
                "records[5].UseTime=0\n" +
                "records[5].UserID=6\n" +
                "records[5].UserType=0\n" +
                "records[5].VTOPosition=\n" +
                "records[5].ValidDateEnd=2037-01-02 01:00:00\n" +
                "records[5].ValidDateStart=2019-01-02 00:00:00\n" +
                "records[6].CardName=ANTONIO AZAMBUJA\n" +
                "records[6].CardNo=\n" +
                "records[6].CardStatus=0\n" +
                "records[6].CardType=0\n" +
                "records[6].CitizenIDNo=\n" +
                "records[6].Doors[0]=0\n" +
                "records[6].DynamicCheckCode=\n" +
                "records[6].FirstEnter=false\n" +
                "records[6].Handicap=false\n" +
                "records[6].IsValid=false\n" +
                "records[6].Password=\n" +
                "records[6].RecNo=8\n" +
                "records[6].RepeatEnterRouteTimeout=4294967295\n" +
                "records[6].TimeSections[0]=255\n" +
                "records[6].UseTime=200\n" +
                "records[6].UserID=7\n" +
                "records[6].UserType=0\n" +
                "records[6].VTOPosition=\n" +
                "records[6].ValidDateEnd=2037-12-31 23:59:59\n" +
                "records[6].ValidDateStart=2023-02-10 10:21:13\n" +
                "records[7].CardName=JoaoSilvaUp\n" +
                "records[7].CardNo=BF79FCC1\n" +
                "records[7].CardStatus=0\n" +
                "records[7].CardType=0\n" +
                "records[7].CitizenIDNo=\n" +
                "records[7].Doors[0]=0\n" +
                "records[7].DynamicCheckCode=\n" +
                "records[7].FirstEnter=false\n" +
                "records[7].Handicap=false\n" +
                "records[7].IsValid=false\n" +
                "records[7].Password=234\n" +
                "records[7].RecNo=9\n" +
                "records[7].RepeatEnterRouteTimeout=4294967295\n" +
                "records[7].TimeSections[0]=255\n" +
                "records[7].UseTime=0\n" +
                "records[7].UserID=8\n" +
                "records[7].UserType=0\n" +
                "records[7].VTOPosition=\n" +
                "records[7].ValidDateEnd=2037-01-02 01:00:00\n" +
                "records[7].ValidDateStart=2019-01-02 00:00:00\n" +
                "records[8].CardName=SOUZA\n" +
                "records[8].CardNo=\n" +
                "records[8].CardStatus=0\n" +
                "records[8].CardType=0\n" +
                "records[8].CitizenIDNo=\n" +
                "records[8].Doors[0]=0\n" +
                "records[8].DynamicCheckCode=\n" +
                "records[8].FirstEnter=false\n" +
                "records[8].Handicap=false\n" +
                "records[8].IsValid=false\n" +
                "records[8].Password=\n" +
                "records[8].RecNo=10\n" +
                "records[8].RepeatEnterRouteTimeout=4294967295\n" +
                "records[8].TimeSections[0]=255\n" +
                "records[8].UseTime=200\n" +
                "records[8].UserID=9\n" +
                "records[8].UserType=0\n" +
                "records[8].VTOPosition=\n" +
                "records[8].ValidDateEnd=2037-12-31 23:59:59\n" +
                "records[8].ValidDateStart=2023-02-10 16:42:37";


        String[] result = StringToArray.retorna(input);
        System.out.println(result.toString());
        for (String i : result) {
            System.out.println(i); }
    }
}